### ISSUE TITLE
Default Fn1 Layer Key for `B` Key seems wrong.

### ISSUE THREAD

**Issue by gb30** [TsFreddie/much-programming-core#10]
The print on the keycap for `B` key shows the `'` (`"`) key, but in the MPC it is the `,` (`<`) key. In other words, the apostrophe key is missing in the MPC.

**Comment by Omniportance** [comment]
Yup, same issue, although I think you mean the Fn1 shows ' and Green Shift-Fn1 shows ", and I am not aware of how to reprogram the Shift-Fn1 layer on this software

**Comment by gb30** [comment]
> Yup, same issue, although I think you mean the Fn1 shows ' and Green Shift-Fn1 shows ", and I am not aware of how to reprogram the Shift-Fn1 layer on this software

I think you misunderstood my problem. I've edited it to make it clearer.

**Comment by Omniportance** [comment]
I understood your problem fine, the green type is supposed to be " which is supposed to be activated via Shift-Control-B, but in the MPC that isn't the default option, nor is it in the firmware (my keyboard shipped with the B key typing , < instead of ' "), and it is not an available option for programming in the MPC.

However, if you look at the Pull Requests, someone else has partially addressed this issue with a workaround, although it doesn't solve some of the other issues with the MPC programmability of secondary keystrokes and default, it does fix the default firmware being off from the keycap.

Additionally, apparently this issue varies by keyboard, depending on when it was built, some of them the default is correct to the keycap, and others the defaults are rather different, due to different firmware editions and keycap variants.

**Comment by TsFreddie** [comment]
1. You can do this
![change](https://user-images.githubusercontent.com/3797859/84189219-d7bf4000-aa8c-11ea-92cb-67f91a6bf0b3.gif)

2. The v2.9 applied this key change by default
