### ISSUE TITLE
[Feature Request]: Allow more macros

### ISSUE THREAD

**Issue by tim6her** [TsFreddie/much-programming-core#14]
The original MPC firmware of [Vortex](http://vortexgear.tw/mpc/index.html) allows 60 macros, while *much programming core * allows for only 20.

Bumping the number of macros would allow me, to use my core in combination with my iOS devices.

**Comment by TsFreddie** [comment]
The macro limit is only a indicator, you can add as many as you want but I doubt it would work. The firmware is unmodified, it is exactly the same as the official one. The 60 macros limit in the MPC firmware is false as some already discovered (https://github.com/TsFreddie/much-programming-core/issues/7, https://github.com/TsFreddie/much-programming-core/issues/4).

Again, **I didn't modified the firmware NOR the binary generation code.** Functionally this project is exactly the same as the official MPC albeit the official MPC has a poorly programmed frontend which make some of the features inaccessible. So if you make more than 20 macros in a profile in the official MPC, it likely won't work as advertised.

I think by 60 macros they meant 20 per profile and they allow you to have 3 profiles, but somehow they just say 60 on the web app and called it a day. By that logic you can have 80 using this tool since the indicator is per profile and this tool allows you to modify the default profile as well.

**Comment by tim6her** [comment]
Hi @TsFreddie , thanks for your prompt reply! I see.

Anyway, great work on much-programming-core! Knowing that this exists, gave me the confidence to purchase a core.
