### ISSUE TITLE
Pn Key macros suddenly don't work

### ISSUE THREAD

**Issue by codebroker40** [TsFreddie/much-programming-core#17]
Hi. I've been using MPC for about 6 months, and I created macros for Pn + other key to type symbols (for example Pn + a does shift 2 to type @). Yesterday I tried to use a macro and it just suddenly didn't work: Rather than getting a symbol, it just typed the normal key. I tried reflashing my layout, and the same problem happened. I understand this probably isn't a problem with MPC, but I didn't know where else to go to try to get help. Thanks.

**Comment by TsFreddie** [comment]
I know it is been awhile. I've updated my MPC with a new binary generation routine which might help with missing keys and macros. 

Do note that some issues might also because the macro limits or the binary size (memory usage). The MPC now has indicators for these limits as well, so try your best to stay in range.

If you still have problems with the new version, feel free to leave a comment.

**Comment by codebroker40** [comment]
Thanks for the response. I tried the new generation and I had the same problem. I just decided to go back to the default firmware, and when I tried to program a key the way the Vortex manual describes, my Pn key just doesnt work, so I think it's just broken unfortunately. I'm closing this issue.
