### ISSUE TITLE
add firmware modifiers to Macro

### ISSUE THREAD

**Issue by gb30** [TsFreddie/much-programming-core#25]
Hi Freddie, 
First, I wanna thank you for this great tool!

I wonder if it's possible to add the on-board firmware modifiers keys (i.e. <kbd>Fn</kbd>, <kbd>Fn1</kbd>, and <kbd>Pn</kbd>) when defining macros.
Currently they are not available when defining macros. If it's possible, it would be very useful in the following scenario.

If I want to press the shifted layer of the number keys, I need to either 
- press <kbd>Shift</kbd>+<kbd>Fn1</kbd>+<kbd>NumberKey</kbd>
- or define a macro on for example the <kbd>Pn</kbd> layer, then I just have to press <kbd>Pn</kbd>+<kbd>NumberKey</kbd>

The second method is preferred as it requires less key press and is similar to the typical <kbd> Shift</kbd>+<kbd>NumberKey</kbd>, but in this way, one would need to define a macro for each number key, which is cumbersome to do but still fine. The other issue is, one will run out of macros very quickly, as the board only supports a maximum of 20 macros.

If the onboard firmware modifiers can be added to macro definition, then only one macro is needed. For example, one can define the base layer of a key as <kbd> Shift</kbd>+<kbd>Fn1</kbd>, the macro type is until release, then it will work with all <kbd>Fn1</kbd> layer keys, saving a huge amount of macros.

**Comment by gb30** [comment]
Tried to add it myself. But unfortunately, it seems not supported by the firmware. I could define the Macro (see the screenshot below), but after flash it to the keyboard, it just doesn't work as intended, instead it triggers some weird inputs. I guess there's a reason that they were not included in the first place.

I wonder if it's possible at all ...

![ADD FN1](https://user-images.githubusercontent.com/59454783/121816477-dd280b00-cc49-11eb-9d9f-e6e496a27da9.jpg)

**Comment by TsFreddie** [comment]
Probably not possible if you already tried it. I can't change the firmware behavior.

I think in the firmware, the modifiers key ids are different from actual Fn1 Fn and Pn. For example, the L1 switch is actually just Fn+O, but it is not done by macro, instead the keyboard can refer to a internal key map that is fixed.

My guess is when you use Fn1 in macro, it can only check the internal key map instead of the custom layout. probably because 1. they didn't thought of it and 2. it would be really easy to create infinite loops even if they did thought of it and lock your keyboard.

**Comment by gb30** [comment]
Guess you're right. When I tried it, the <kbd>shift</kbd>+<kbd>Fn1</kbd> sometimes sends <kbd>l</kbd> infinitely. Thanks for the information.
