### ISSUE TITLE
[Feature request] ability to assign !@#$%^&*() symbols to a key.

### ISSUE THREAD

**Issue by coquizen** [TsFreddie/much-programming-core#3]
I see in your code that key mapping corresponds to HID scan code standard. Is there way you can add a secondary keyboard map for the shifted keys? Namely the shifted number keys? Or does this have to be done using a macro? If so, what's the minimum time interval would I need to each key press and release?

**Comment by PushkaCom** [comment]
that's how I did it (man I love this system so much) - 
the default is 10 ms which seems like twice the speed of the core default lumbering macro, but pok3r seems faster still, I'm using 5ms

**Comment by coquizen** [comment]
Ah, ok thanks. Are you using the Core as a daily driver? If so, mind sharing your keymap? Always looking for improvements. Here is [mine](https://i.imgur.com/CEDkbtS.png).

And yes, I concur, TsFreddie's work here is phenomenal.

**Comment by PushkaCom** [comment]
L1 is Colemak, L2 is not used, but it has errors now anyway, L3 is my macros, email addresses, addresses, phone numbers, my full name , etc. 
L4 is qwerty and I use Fn ctrl, win, alt to switch layers ~~ 
 https://photos.app.goo.gl/2GoQQgNxNARJgRvr5
I'm using it daily at work with my Pok3r also connected , just until I get super used to it, I mainly wanted it for writing meeting notes while on the road, but I may just keep using it - I have a square num pad using the Fn layer, so it's easier than the pok3r, and I can easily take it into meeting rooms at work - I have brown switches and it's really quiet ~~~ love it <3

EDIT - 
I had issues with buttons not working, but I deleted some Pn items and it's all fine now, 
I was editing a bunch of times and everything was awesome but suddenly some things have stopped working, I was messing with adding a Pn layer so maybe that messes with the code,,

**Comment by TsFreddie** [comment]
There's a hard cap on how many macros you can have. Someone said 20, but I sometime only get 10.

I've been trying to find a workaround for quite some time now.

Here's what I (might) have now:

In the binary file, each macro have a index number. And the firmware reject a macro if its index exceed certain number. But iirc, a key bind to a memory offset instead of the index.

**Comment by TsFreddie** [comment]
And yes, since the key only bind to hid key code, macro is the only way to input special characters. And yet Vortex didn't provide enough macro space for us to use.

**Comment by PushkaCom** [comment]
Ah, I see - after some messing around - I have gotten the layers to work 100% 
Yeah - I had to remove some things because after a certain number of macros they just did nothing ~ but all is well, i have actually put most things I need on 1 layer thanks to the Pn layer, and removing some not-so-needed stuff ~ 
Thank you for the work - it's the best !!!
