### ISSUE TITLE
Cannot Program Secondary Keystrokes

### ISSUE THREAD

**Issue by Omniportance** [TsFreddie/much-programming-core#9]
When I am using the editor, I cannot program keystrokes such as " or @ because I can only click the default keys such as ' or 2.

Additionally, I do not understand what the "Fn" Layer and the "Pn" Layer mean.

**Comment by isti115** [comment]
I'm not an expert, but from what I know, the keyboard sends KEYS, not CHARACTERS. The keys (or combination of keys) are then converted to the characters by the operating system that handles the input using a keymap. Since there is no separate "@" key (at least on the default US layout) you cannot send that by itself, the system translates the "Shift + 2" combination to "@", so if you really need to have a dedicated key for "@", you can use a macro, but as you can see in #7, you only have a limited number of those.

**Comment by TsFreddie** [comment]
as @Isti115 pointed out, vortex core only send key strokes that you can find on a physical keyboard. You can make macros for this, but be careful not to exceed the 20 macros per profile limit.
